### ISSUE TITLE
go mod tidy，An error occurred

### ISSUE THREAD

**Issue by Duanraudon** [polynetwork/fabric-relayer#1]
![image](https://user-images.githubusercontent.com/34836995/120445074-d6cca000-c3ba-11eb-90ff-ba556aead5d6.png)

**Comment by chenquanyu** [comment]
![image](https://user-images.githubusercontent.com/4393234/120921920-d3a61c80-c6f8-11eb-944d-cdf29c54c9d6.png)
Yes, the pkg folder is missing for this repository. @tanZiWen

**Comment by natureoo** [comment]
may i know where to find this pkg folder in fabric-repayer
